name: flutter_voice_control_example_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  sherpa_onnx: ^1.12.11
  permission_handler: ^12.0.1
  path_provider: ^2.1.3
  path: ^1.9.0
  record: ^6.1.1
  shared_preferences: ^2.5.3
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/models/
    - assets/models/sherpa-onnx-streaming-zipformer-en-kroko-2025-08-06/
